### PR TITLE
Drop .NET 4 support. Prepare for 2.5.0.

### LINKED ISSUE #38: Microsoft BCL Build warnings
Ever since updating to the latest nuget package I'm seeing:

Severity	Code	Description	Project	File	Line
Warning		All projects referencing Exceptionless.Core.csproj must install nuget package Microsoft.Bcl.Build. For more information, see http://go.microsoft.com/fwlink/?LinkID=317569.	Exceptionless.Insulation		

Please remove this dependency for 4.5+ projects...

### LINKED ISSUE #41: Json Serialization Drops Name fields
When I create a DatabaseReader object and complete a search for an IP that exists in the database, the CityResponse object contains values for the .Name fields.  For example, CityResponse.City.Name =SomeCity.  When I serialize this object using  JsonConvert.SerializeObject(CityResponse) (part of Newtonsoft.Json.dll), the Name properties are not serialized.  If I then use JsonConvert.DeserializeObject<CityResponse>(jsonstring) to deserialize back to the object the .Name fields are null.  Is there a way to ensure that the .Name fields are serialized with the rest of the object?

Example:
 var city = loReader.City(lstrIP); // city.City.Name = cityname
var json = JsonConvert.SerializeObject(city); 
var city2 = JsonConvert.DeserializeObject<MaxMind.GeoIP2.Responses.CityResponse>(json); //city2.City.Name = null

### PR DESCRIPTION
**Pull request by oschwald**
* IMPORTANT: The target framework is now 4.5.2. Microsoft is ending support
  for 4.0, 4.5, and 4.5.1 on January 12, 2016. Removing support for these
  frameworks allows us to remove the dependency on the BCL libraries and fixes
  several outstanding issues. Closes #38, #39, #40, and #42.
* The assembly version was bumped to 2.5.0.
* Classes subclassing `NamedEntity` now have a default locale of `en`. This
  allows the `Name` property to be used (for English names) when the object is
  deserialized from JSON. Closes #41.
* The `locale` parameter for the `DatabaseReader` and `WebServiceClient`
  constructors is now an `IEnumerable<string>` rather than a `List<string>`.
* The tests now use NUnit 3.

### CODE REVIEW

File: GeoIP2/DatabaseReader.cs [hunk 1]
```diff
@@ -39,9 +39,9 @@ public DatabaseReader(string file, FileAccessMode mode = FileAccessMode.MemoryMa
         /// <param name="file">The MaxMind DB file.</param>
         /// <param name="locales">List of locale codes to use in name property from most preferred to least preferred.</param>
         /// <param name="mode">The mode by which to access the DB file.</param>
-        public DatabaseReader(string file, List<string> locales, FileAccessMode mode = FileAccessMode.MemoryMapped)
+        public DatabaseReader(string file, IEnumerable<string> locales, FileAccessMode mode = FileAccessMode.MemoryMapped)
```
Comment (eilara) [inline GeoIP2/DatabaseReader.cs]: There are still some places where are expecting specific implementations instead of interfaces, in public & protected signatures. Is that to help the JSON serializer?

Comment (eilara) [inline GeoIP2/DatabaseReader.cs]: Is there a test that shows #41 (https://github.com/maxmind/GeoIP2-dotnet/issues/41) is fixed?

Comment (oschwald) [inline GeoIP2/DatabaseReader.cs]: @eilara, public signatures should be using IEnumerable (although I'll re-review). I didn't bother with protected ones, but maybe I should.

Re: test, the deserialization test now tests this (as it doesn't explicitly set the locale anymore).

Comment (oschwald) [inline GeoIP2/DatabaseReader.cs]: Ah, I see the public ones you are referring to. I didn't even realize there was a public constructor there. I'll fix. Thanks.

Comment (eilara) [inline GeoIP2/DatabaseReader.cs]: Have you tried building the git project GeoIP-dotnet or a project that nuget-depends on it, on the Microsoft Linux IDE? Omnisharp is dying for some reason, and that is an important component. Maybe supporting it out-of-the-box would bring more users.

Comment (eilara) [inline GeoIP2/DatabaseReader.cs]: I thought maybe some implementations were there for the sake of the JSON serializer. It is the component I blame whenever I don't understand something here, because it is a bit invasive.

Comment (oschwald) [inline GeoIP2/DatabaseReader.cs]: Omnisharp dies when using the GeoIP2 package from NuGet?

Comment (oschwald) [inline GeoIP2/DatabaseReader.cs]: FYI, I fixed the interface issues where it was possible without breaking the public API.
